services:
  ai-assistant:
    build: .
    container_name: legendarycorp-ai-assistant
    ports:
      - "5252:5252"
    environment:
      - LOG_LEVEL=WARN
      - CHROMA_DB_VISUALIZER=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KNOWLEDGE_DOCS_PATH=/app/data/knowledge-docs
      - CHROMA_DB_PATH=/app/data/vector_db
      - COST_DB_PATH=/app/data/costs
    volumes:
      - ./data/vector_db:/app/data/vector_db
      - ./data/knowledge-docs:/app/data/knowledge-docs
      - ./data/costs:/app/data/costs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5252/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-network

  # Optional: Add Redis for session management and caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: ai-assistant-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - ai-network

networks:
  ai-network:
    driver: bridge

# volumes:
#   redis_data:
